### ISSUE TITLE
Add blueprint for Ember CLI

### ISSUE THREAD

**Issue by wwilsman** [ef4/liquid-fire#107]
Since Liquid Fire embraces Ember CLI, it would be beneficial to have a [blueprint](http://www.ember-cli.com/#generators-and-blueprints) available and be able to type `ember generate transition <transition-name>` and have the proper files and directories be created (maybe along with other helpful blueprints).

**Comment by lukesargeant** [comment]
Pull request for this: #166

**Comment by ef4** [comment]
#166 merged.
