### ISSUE TITLE
Temporary solution for modal transitions?

### ISSUE THREAD

**Issue by samselikoff** [ef4/liquid-fire#153]
I saw the note in the docs about how the API for modal transitions is still under development.

Is there a temporary fix for now, for instance if I wanted the dialog to appear/disappear instantly (no transition)?

**Comment by samselikoff** [comment]
btw, the modal implementation is one of the best I've seen. great work!

**Comment by ef4** [comment]
Yes, you can define your own transition named modal-popup that doesn't
animate anything. That should override.

**Comment by samselikoff** [comment]
awesome, ty!

**Comment by samselikoff** [comment]
Could you give a quick example of a noop? I tried

**Comment by ef4** [comment]
That's nearly it, but `insertNewView` is a function so you need to call it and return the resulting promise.

**Comment by samselikoff** [comment]
So this?

```js
export default function(oldView, insertNewView, opts) {
  return insertNewView();
});
```

Still not working, interestingly even though the view seems to get rendered (the DOM nodes are there), `visibility` is still `hidden` on the `.liquid-child` that wraps the modal.

**Comment by ef4** [comment]
Oh yeah, my bad: the animations also normally make the new view visible. Here's a complete noop transition:

````js
export default function noop(oldView, insertNewView) {
  return insertNewView().then(function(newView){
    if (newView){
      newView.$().css({
        display: '',
        visibility: ''
      });
    }
  });
}
````

**Comment by samselikoff** [comment]
Perfect, thanks!
