### ISSUE TITLE
Not working with Ember Canary

### ISSUE THREAD

**Issue by chrism** [ef4/liquid-fire#158]
Hi,

I've been using the library fine with HTMLBars and a slightly older version of Ember Canary, but I've just updated to Ember CLI 0.1.5 with

````
Ember         : 1.11.0-beta.1+canary.dca9c74d
Ember Data    : 1.0.0-beta.14.1
```

& using the latest version of liquid-fire (0.16.0)

Now i'm getting an error in the console saying

```
router-dsl-ext.js:41 Uncaught TypeError: Cannot set property 'modals' of null
```

and nothing in the display.

If I remove liquid-fire (and changing liquid-outlets & liquid-ifs to outlets & ifs) & it works again which makes me think that the error must be related to the library.

Any ideas why this is happening or possible fixes would be really appreciated.

**Comment by rlivsey** [comment]
There are a number of fixes for Canary in master, so the next release of liquid-fire should resolve those.

In the meantime you could set package.json to point to master:

```
liquid-fire": "git+https://github.com/ef4/liquid-fire.git"
```

**Comment by chrism** [comment]
Thanks @rlivsey I'll check it out.

**Comment by rlivsey** [comment]
No worries, let me know if you run into any other issues with Canary, I've been running it in my app for the past day without any problems so far.

**Comment by chrism** [comment]
Seems to work fine now using master, thanks again @rlivsey 

:+1:
