### ISSUE TITLE
Stack modals?

### ISSUE THREAD

**Issue by samselikoff** [ef4/liquid-fire#159]
Is it possible to stack modals? Sort of like navigation stacks in iOS

**Comment by ef4** [comment]
Yes, they do basic stacking now. Not visually, but logically.

If you have a modal on screen and another modal suddenly becomes active, it will replace the older one. Then when it goes away the older one will come back.

The one thing about this that's a bit wacky right now is that if you boot your app in a state such that two modals are both active, you don't have a way of breaking the tie reliably one way or the other. They race in an implementation-dependent way.

**Comment by samselikoff** [comment]
works for me, thanks!
