### ISSUE TITLE
IE 8 Broken

### ISSUE THREAD

**Issue by drewcovi** [ef4/liquid-fire#161]
from transition.js 

there have been a few issues in the past around the finally in promises in ie8, im running the latest ember-cli with the latest liquid-fire

```
        return this._ran = this._invokeAnimation().then(function(){
          self.maybeDestroyOldView();
        }, function(err){
          return self.cleanupAfterError().then(function(){
            throw err;
          });
        }).finally(function(){
          self.transitionMap.activeCount -= 1;
        });
```

**Comment by drewcovi** [comment]
I'm guessing for some reason safe-recasting isnt working here?

**Comment by ef4** [comment]
Is this still an issue for you? Are you using ember-cli or the prebuilt releases?

**Comment by ef4** [comment]
Feel free to reopen if this is still an issue.
