### ISSUE TITLE
Make it easier to override modal animation

### ISSUE THREAD

**Issue by alexismangin** [ef4/liquid-fire#162]
Hi,
I was wondering if is it possible to change the animation of the modal?
I'd like to display my modal from bottom to top, without fading.
If we can, can you please provide an example?
If we can't, maybe there is an alternative solution using liquid-outlet?

Thanks.

**Comment by ef4** [comment]
Yes, the best way to do it at present is to copy the transitions/modal-transition.js into your own app to override the built in one and edit it.

I intent to add an easier way, but that's what you can do for now.

**Comment by alexismangin** [comment]
Thanks! I look forward to this easier way!

**Comment by jagthedrummer** [comment]
@alexismangin I just discoverd that this is now possible: http://ef4.github.io/liquid-fire/#/modals/animation

I just did this to get my modals coming in from the top:

```javascript
  this.transition(
    this.inHelper('liquid-modal'),
    this.use('explode', {
      pick: '.lf-overlay',
      use: ['cross-fade', { maxOpacity: 0.5 }]
    }, {
      pick: '.lm-container',
      use: 'toDown'
    })
  );
```

**Comment by alexismangin** [comment]
That's awesome, thanks for the note @jagthedrummer!
