### ISSUE TITLE
View is hidden.

### ISSUE THREAD

**Issue by ziflex** [ef4/liquid-fire#163]
Hi there,
I've faced with an issue when my view is rendered but it's hidden (it has 'transform: translateY(0)'). 
Once I  change 'liquid-outlet' to regular 'outlet' everything gets fine.

UPD: My views have 'layout' and after removing 'layoutName' property - they become visible.

**Comment by ef4** [comment]
translateY(0) wouldn't hide your view, so something else must have been going on. I suspect this was some other CSS problem, and that removing your layout accidentally solved it.

Please reopen if you are still having a problem or can add more detail.

**Comment by GendelfLugansk** [comment]
I faced the same issue - sometimes content inside liquid-container is hidden and disabling translateY(0) fixes it. But this happens only in Chromium/Chrome and not for all containers. Some containers are fine and some are not on the same page, and I can't find any other css property that affects visibility of "invisible" content. Looks like browser's bug.
