### ISSUE TITLE
Initializer Issue (ember-cli 0.1.9)

### ISSUE THREAD

**Issue by cmkornell** [ef4/liquid-fire#165]
```javascript
define('test-app/initializers/liquid-fire', ['exports', 'liquid-fire', 'ember'], function (exports, liquid_fire, Ember) {

  'use strict';

  exports['default'] = {
    name: "liquid-fire",

    initialize: function (container) {
      if (!Ember['default'].$.Velocity) {
        Ember['default'].warn("Velocity.js is missing");
      } else {
        var version = Ember['default'].$.Velocity.version;
        var recommended = [0, 11, 8];
        if (Ember['default'].compare(recommended, [version.major, version.minor, version.patch]) === 1) {
          Ember['default'].warn("You should probably upgrade Velocity.js, recommended minimum is " + recommended.join("."));
        }
      }

      liquid_fire.initialize(container);
    }
  };

});
```
```"liquid_fire" is undefined.```

I'm guessing this has something to do with Ember CLI now using ember-cli-6to5?

**Comment by corpulentcoffee** [comment]
I have this same problem. It looks like the upgrade for broccoli-es6modules from v0.3.1 to v0.4.0 is what broke it.. maybe.. that's what broke it for me when I bisected it, anyway.

**Comment by corpulentcoffee** [comment]
For what it's worth: I was able to get Liquid Fire working with ember-cli 0.1.9 by [changing the `liquid-fire` imports to use `liquid-fire/index` instead](https://github.com/corpulentcoffee/liquid-fire/compare/compat-0.1.9).

I'm not sure if this is the correct/best way to fix this as I don't know what exactly the problem is with the transpiling.

**Comment by cmkornell** [comment]
Hrm. Oddly, after clearing bower's and npm's cache a million times and restarting, Liquid Fire works with ember-cli 0.1.9 without modification. Not sure how we were both seeing that issue, though. Maybe an upgrade snafu? IDK.

**Comment by cmkornell** [comment]
Yeah, it doesn't seem like you should have to define "index" considering node conventions, but hey, until it's fixed...it's a quick workaround.

**Comment by rlivsey** [comment]
Just been discussing this with @rwjblue on the #ember-cli IRC channel.

Looks like an issue with the move to esperanto for module compilation. It's not handling the re-exporting in `index.js` properly so the imported object in the initializer here isn't correct.

The latest master of loader.js fixes some issues, but not this one just yet.

**Comment by cmkornell** [comment]
Good to know. Thanks, @rlivsey.

**Comment by drewcovi** [comment]
@rlivsey so quick check then... is this an issue for liquid-fire or for esperanto?

Thanks for the quick fix, just want to know where to look to tuck this one away when the fix lands.

**Comment by rlivsey** [comment]
@drewcovi from what I understand after chatting to @rwjblue, it's an issue with Ember's loader.js as opposed to liquid-fire or esperanto.

**Comment by rwjblue** [comment]
@stefanpenner identified the issue, and submitted https://github.com/esperantojs/esperanto/pull/80/files to fix upstream.

**Comment by alexdiliberto** [comment]
@rwjblue @stefanpenner Awesome! :+1:
