### ISSUE TITLE
Liquid Modal as a route?

### ISSUE THREAD

**Issue by jgodi** [ef4/liquid-fire#168]
Is is possible to have a liquid modal be a route?

Here is what I have:

* List of users, click a user and a user modal pops up
* Currently this goes to the user.info route that is just my implementation of a modal
* Refresh and it will automatically bring up the modal

I do this to leverage Ember Data since the user.info route will fetch more detailed info about the user.

I am integrating Liquid Fire (amazing library btw, great work!) and I would like this modal to use the liquid fire modal. I can seem to find any examples of this. Can this be accomplished?

Thanks!

**Comment by jgodi** [comment]
Figured it out. Just loading the modal on the route ```withParams: 'model'``` will load the modal up when the data is resolved.

**Comment by ef4** [comment]
Glad you were able to solve your case. I think we need some improvement to
either the docs or api to make this scenario easier for people to figure
out.

**Comment by jgodi** [comment]
Once I get everything worked out and working perfectly, I will submit a PR for the docs.
