### ISSUE TITLE
transitions.css 404s on fresh install?

### ISSUE THREAD

**Issue by johnmcdowall** [ef4/liquid-fire#174]
I just created a brand new Ember-cli (0.1.12) project, added liquid-fire with:

`ember install:addon liquid-fire`

I then created two routes in my Ember application and booted up the `ember serve`. 

Straight away I get a `transition.css` 404 in the console along with a bunch of other errors. 

To be expected? 

![screenshot 2015-02-12 14 17 13](https://cloud.githubusercontent.com/assets/237175/6178246/e45244c0-b2c1-11e4-87fa-cae0db342dad.png)

**Comment by ef4** [comment]
Is your app named "transitions"?

**Comment by ef4** [comment]
Please reopen if you are still having a problem and can add more detail.

**Comment by johnmcdowall** [comment]
Hi @ef4, yes sorry. Didn't remember new Ember-cli projects 404ing on the stylesheets before either. Thanks!

**Comment by ef4** [comment]
Yeah, it's kinda lame that they do, probably worth addressing in ember-cli.

**Comment by johnmcdowall** [comment]
Ah ha, looks like it's just been addressed: https://github.com/ember-cli/ember-cli/commit/e4f45a549c9b4bdec93dec81dafcf4fe7823145d
