### ISSUE TITLE
Route Transition Not Applying?

### ISSUE THREAD

**Issue by al3x-edge** [ef4/liquid-fire#175]
I can't seem to get the route transitions in a new project to trigger.  Apologies if this is the wrong place.  Freshly generated ember-cli projected and installed with `npm install --save-dev liquid-fire` and restarted `ember server`.

Currently the routes just transition like normal, although I do see a `.liquid-container -> .liquid-child` duo in the DOM. Hope the demo is simple enough to reproduce.  Trying out the route animations before I decide I'm running in Ember for this project.

**transitions.js**
```js
export default function(){
  this.transition(
    this.toRoute('index'),
    this.use('fade')
  );
  this.transition(
    this.toRoute('modelYear'),
    this.use('fade')
  );
}
```

**router.js**
```js
import Ember from 'ember';
import config from './config/environment';

var Router = Ember.Router.extend({
  location: config.locationType
});

Router.map(function() {
  this.route('modelYear');
});

export default Router;
```

**templates/application.hbs**
```hbs
{{liquid-outlet}}
```

**templates/index.hbs**
```hbs
<h1> Hello, world!</h1>
{{#link-to 'modelYear'}}Model Year{{/link-to}}
```

**templates/model-year.hbs**
```hbs
<h1>MODEL YEAR!</h1>
{{#link-to 'index'}}Home{{/link-to}}
```

**Comment by ef4** [comment]
It looks like we don't automatically dasherize route names, so try changing this:

````js
this.toRoute('modelYear'),
````

to this:

````js
this.toRoute('model-year'),
````

When I reproduced your setup, that was enough to make that rule work. The other rule (`toRoute('index')`) was already working.

**Comment by al3x-edge** [comment]
@ef4 I must still be doing something wrong. I still am seeing normal page transitions with the change to `this.toRoute('model-year')`. Tried using `{{liquid-outlet use="fade"}}` -- route transitions fade out and back in.  I can grant you access to the repository if you are willing to take a look.

**Comment by al3x-edge** [comment]
@ef4 Looks like just something with that project?  Picked up the newest 2.0-beta1 of cli using Ember 1.10.0 and everything seems to be fine after liquid-fire install. I'll close for now as I've moved on, but I'll keep the repo there in case you would like to dig farther. 

Great library btw. Keep up the good work!
