### ISSUE TITLE
Transition map

### ISSUE THREAD

**Issue by zac156** [ef4/liquid-fire#182]
Hi there,

Thanks for this awesome lib. 

When doing a transition between routes does one need to define every single transition to and from every single route?

For example: I have three different routes: documents, financials and policies.

Does this mean that I have to use the transition map to define every possible transition and what needs to take place. e.g:

documents -> policies
documents -> financials

financials -> policies
financials -> documents

policies -> documents 
policies -> financials 

And then a toRoute and fromRoute for every transition? Maybe I am misunderstanding how this works but if so could someone please help clarify this matter for me?

Is it not possible to say 'if ANY route transitions into documents/policies/etc.. then do this transitional effect'?

Thanks so much!

**Comment by al3x-edge** [comment]
@zac156, below is a sample similar to what I'm currently using.  I also have situations where I match above those transitions coming from a certain route for more specific animations.

```js
this.transition(
   this.toRoute('documents'),
   this.use('fade')
);
this.transition(
   this.toRoute('policies'),
   this.use('fade')
);
this.transition(
   this.toRoute('financials'),
   this.use('fade')
);
```

**Comment by zac156** [comment]
Perfect, thank you!

**Comment by ef4** [comment]
If these are the only three routes that will ever appear in that particular liquid-outlet, you can simplify even further. Put a class on the liquid-outlet:

    {{liquid-outlet class="my-main-outlet"}}

and then say:

    this.transition(
        this.hasClass('my-main-outlet');
        this.use('fade');
    );
