### ISSUE TITLE
Dynamic classnames don't seem to map to the transition map

### ISSUE THREAD

**Issue by chrism** [ef4/liquid-fire#183]
Hi,

I'm trying to slide content either left or right depending on which button gets pressed.

My model is a recordArray which is changed via a refresh of queryparams , so don't think using a model matcher such as fromModel & toModel will work for me.

Instead i'm using the liquid-with template helper

```handlebars
{{#liquid-with model as currentModel class=directionClass}}
<ul class="search-results-list">
  {{#each currentModel as |item|}}
    {{search-item item=item added=addedImages action="fetchImage"}}
  {{else}}
    <h2>Sorry, it seems like there was a problem getting the images — please try reloading the page.</h2>
  {{/each}} 
</ul>
{{/liquid-with}}
```

in my controller I set a property like this

```javascript
directionClass: 'testing-container',
```

& it works fine with a transition map like this...

```javascript
this.transition(
  this.hasClass('testing-container'),
  this.use('fade', {duration: 2000}) 
);
```

this also works when I set a different initial value for the directionClass property & transition ie

```javascript
directionClass: 'testing-container-previous',
```

```javascript
this.transition(
  this.hasClass('testing-container-previous'),
  this.use('toLeft', {duration: 2000}) 
);
```

My problem is that if, before firing the model refresh I try to pre-emptively set the correct class name for the animation ie by

```javascript
  actions: {
    changePage: function(direction, offset, count) {
      if (direction === "-1") {
        Ember.Logger.log('previous...');
        this.set('directionClass', 'testing-container-previous');
      } else {
        Ember.Logger.log('next...');
        this.set('directionClass', 'testing-container-next');
      }
      return true;
    },
  }
```

Then it seems to completely break the animation & no transition is used.

Would really appreciate any suggestions as to why this happens, many thanks.

**Comment by chrism** [comment]
I've been trying to make a JSBin to illustrate this issue to see if it might help get a response.

Unfortunately the latest builds of Liquid Fire 0.18.0 don't seem to work with JSBin now & the latest versions of Ember/template compiler.

I'm using Ember Beta (1.11.0-beta.3) with latest Velocity / Liquid Fire like this

```html
<link href="http://jsbin-assets.s3.amazonaws.com/liquid-fire-0.18.0.css" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="http://builds.emberjs.com/beta/ember-template-compiler.js"></script>
<script src="http://builds.emberjs.com/beta/ember.debug.js"></script>
<script src="http://jsbin-assets.s3.amazonaws.com/velocity.1.2.2.min.js"></script>
<script src="http://jsbin-assets.s3.amazonaws.com/liquid-fire-0.18.0.js"></script>
```
http://jsbin.com/rideto/2

But if I change

```html
{{#if isWorking}}
  <p>is working</p>
{{/if}}
```

to

```html
{{#liquid-if isWorking}}
  <p>is working</p>
{{/liquid-if}}
```
I get errors in the console...

```
liquid-fire-0.18.0.js:1784 Uncaught SyntaxError: Unexpected token ILLEGAL
Uncaught Error: Assertion Failed: A helper named `liquid-if` could not be found
```

http://jsbin.com/rideto/3

Would really appreciate any help as to whats going on — or an example JSBin with it working as all the old Liquid Fire JSBins I could find no longer work.

Thanks!

**Comment by ef4** [comment]
You should use model-based rules for this. The rules can be arbitrary functions, so it doesn't matter that the models are actually record arrays.

    this.transition(
        this.toModel(function(newModel, oldModel) {
          // return true if this pair of models should transition via toLeft, otherwise they will transition via toRight
        }),
        this.use('toLeft'),
        this.reverse('toRight')
    );

**Comment by ef4** [comment]
The JSBin issue is due to #170.

**Comment by chrism** [comment]
OK thanks, I've used that approach & added some metadata to my model so that I could access it via model.get('meta.offset') to be able to decide which direction.

Much appreciated.

:+1:
