### ISSUE TITLE
Trouble with the Modal example

### ISSUE THREAD

**Issue by urahonky** [ef4/liquid-fire#184]
Hello!

First of all I just want to say thank you for making this addon for Ember CLI. Transitions and Modals are a huge pain in the butt for me and having an addon would take a lot of stress off my mind.

Now on to the issue:

I followed your http://ef4.github.io/liquid-fire/#/modals tutorial. Whenever I click the button the modal window pops up at the bottom of the page (but does not pop out of the page). 

I'm using Ember CLI version: 0.2.0-beta.1 and Ember v 1.10 with liquid-fire v1. 0.17.0 (since I'm not on Ember v1.11 yet). 

Here's the code I'm using:

controller:
```
    export default Ember.Controller.extend({
        queryParams: ['salutation', 'person'],
        salutation: null,
        person: null,
        modalMessage: "bound text for modal"
    });
```
router.js:
```
    this.modal('hello-modal', {
        withParams: ['salutation', 'person'],
        otherParams: {
            modalMessage: "message"
        },
        actions: {
            changeSalutation: "changeSalutation"
        }
    });
```
hello-modal.hbs:
```
<div>{{salutation}} {{person}}!</div>
<div>{{input value=message class="modal-input"}}</div>
<button {{action "gotIt"}} class="done">Thanks</button>
<button {{action "change"}} class="change">Change</button>
```
components/hello-modal.js:
```
export default Ember.Component.extend({
	classNames: ['hello-modal'],
	actions: {
	    gotIt: function() {
	      this.sendAction('dismiss');
	    },
	    change: function() {
	      this.sendAction('changeSalutation');
	    }
	  }
});
```
template:
```
{{#link-to (query-params salutation="Guten tag" person="Stef") tagName="button"}}
Try It
{{/link-to}}
```

quick screenshot (this is appended to the bottom of the html page and doesn't pop out like a model window as your example shows):
![modal](https://cloud.githubusercontent.com/assets/6754000/6380635/132239ee-bd09-11e4-9eee-5adc442add45.PNG)

This warning also shows up in my console if it gives any help:
WARNING: You're attempting to render a view by passing boundContextBinding to a view helper without a quoted value, but this syntax is ambiguous. You should either surround boundContextBinding's value in quotes or remove `Binding` from boundContextBinding.
vendor.js:80744 Object

Thank you for your time! If you need any additional information please let me know.

**Comment by urahonky** [comment]
I went ahead and started a fresh project using your tutorial and it worked as intended!

It looks like it's related to broccoli-compass. I spent a few minutes going from the fresh project to my work project and it worked all the way up until I included that node project. When I did that and then updated the Brocfile.js to have:

```
var compileCompass = require('broccoli-compass');
var pickFiles = require('broccoli-static-compiler');
var mergeTrees = require('broccoli-merge-trees');

app.styles = function() {
  var vendor = this._processedVendorTree();
  var styles = pickFiles(this.trees.styles, {
    srcDir: '/',
    destDir: '/app/styles'
  });

  var stylesAndVendor = mergeTrees([vendor, styles, 'public']);

  return compileCompass(stylesAndVendor, {
  	files: 'app' + '/styles/app.scss',
    outputStyle: 'expanded',
    require: 'sass-css-importer',
    sassDir: 'app' + '/styles',
    imagesDir: 'images',
    fontsDir: 'fonts',
    cssDir: 'assets'
  });
};
```

Then when I click the button it just appends it to the page. Here are two screenshots that should hopefully show you what I'm talking about (since before the page had some proprietary information on it):

Before:
![before-modal](https://cloud.githubusercontent.com/assets/6754000/6394143/70523ec2-bd9d-11e4-8dbd-c65cfb284708.PNG)

After:
![after-modal](https://cloud.githubusercontent.com/assets/6754000/6394148/74a71e66-bd9d-11e4-8060-c8f26a7f7741.PNG)

Here are the dependencies that I added that ended up causing the issue:

"broccoli-compass": "^0.2.4",
"broccoli-merge-trees": "^0.2.1",
"broccoli-static-compiler": "^0.2.1",

Which really sucks since we need to use compass for this project (I assume it's compass but really it could be either one of these). I'll dig in a bit more to see if it's something specific that's causing the odd behavior but I'm on a pretty tight deadline for work (which is why I wanted to your use library badly).

**Comment by urahonky** [comment]
Alright I figured out a good workaround that allows me to use your modal windows with our project. What I ended up doing is copying all of your .css from the liquid-fire/vendor/liquid-fire.css file into my app.scss file and then recompiled the project using compass.

As soon as I did that it worked exactly how the demo worked. I hope this helps you and/or future users in getting it working using broccoli-compass!

**Comment by ef4** [comment]
It sounds like using broccoli-compass causes ember-cli to ignore all the CSS from other addons like liquid-fire.

**Comment by urahonky** [comment]
Yeah that's what I suspect. It's possible that including the scss file for liquid-fire could fix it but I haven't tested that yet.

**Comment by ef4** [comment]
It's an ember-cli bug, but it may be fixed by the latest changes on master
there, which do a better job of isolating preprocessor use among addons.

**Comment by urahonky** [comment]
Sounds good to me. Thanks again for this addon.
