### ISSUE TITLE
WARNING: This version of liquid fire requires Ember 1.11 or newer... but on version: 0.2.0-beta.1

### ISSUE THREAD

**Issue by sheriffderek** [ef4/liquid-fire#193]
"WARNING: This version of liquid fire requires Ember 1.11 or newer"

... but I'm on version: 0.2.0-beta.1

Any advice?

**Comment by wolodarsky** [comment]
I believe you are referring to your ember-cli version (0.2.0-beta.1)?

If so, you can update your bower.json in your ember-cli project to use a newer version of ember:

`"ember": "~1.11.0-beta.4",`

**Comment by ef4** [comment]
If you're not ready to use a newer Ember, use the 0.17 series of liquid fire like:

    npm install --save-dev liquid-fire@^0.17.0

**Comment by sheriffderek** [comment]
Thank you for your help. I didn't realize that it was ember itself and not CLI.
