### ISSUE TITLE
Fresh CLI Build failing on Install

### ISSUE THREAD

**Issue by hhff** [ef4/liquid-fire#196]
Working on getting Liquid Fire working with Ember Paper!

```js
ember new app
cd app
ember install:addon liquid-fire
```
application.hbs ->  Change `{{outlet}}` to `{{liquid-outlet}}`

Getting this:

![screen shot 2015-03-07 at 10 58 13 pm](https://cloud.githubusercontent.com/assets/2865404/6544435/8c7df88e-c51d-11e4-9600-65673ec8201e.png)

```bash
$ ember -v
version: 0.1.15
node: 0.10.26
npm: 2.1.8
```

Feel like this is a htmlbars thing, but unsure!

Thanks @ef4 !

**Comment by ef4** [comment]
Your screenshot says:

> This version of liquid fire requires Ember 1.11 or newer.

You are using 1.8.1.

[See here](https://github.com/ef4/liquid-fire#installation) for the instructions on obtaining the correct version to match ember.

**Comment by hhff** [comment]
Gahhh late night hacking.

Thanks @ef4 !
