### ISSUE TITLE
Nested outlets don't work.

### ISSUE THREAD

**Issue by wagenet** [ef4/liquid-fire#204]
A `{{liquid-outlet}}` will not animate transitions if nested within another one. If I change the parent back to a normal outlet, things work as expected. This is on master.

I'll try to put together a reproduction soon.

**Comment by ef4** [comment]
This is a regression on master. The new liquid-outlet implementation is not maintaining stability for its children, which causes the inner liquid-outlet to always get re-rendered.

**Comment by ef4** [comment]
Closed in 22498ae7bc46eb00a09faa785b87afdd90c6b954

**Comment by wagenet** [comment]
Thanks :)
