### ISSUE TITLE
Explode: height / width vs outerHeight / outerWidth

### ISSUE THREAD

**Issue by green-arrow** [ef4/liquid-fire#205]
This is meant to start a discussion on the use of jQuery `.width()` and `.height` in the `explode` animation (also present in `flyTo`). Was there a specific reasoning behind choosing these two methods instead of `outerWidth()` and `outerHeight`?

To give some context as to what prompted this question, I am displaying a list of items in a `<ul>`. Using `liquid-with`, I am animating items with the `explode` transition when the user applies filters. The issue is that my list items have padding, and the use of `width()` and `height()` cause "jerky" animations, because the _real_ width / height are applied after the animation is over, causing the item to "snap" into place.

I feel that with the widespread use of `border-box`, padding and border are taken into account in the width / height calculation for elements most of the time. That being the case, it would make sense to me to use `outerHeight` and `outerWidth` in these transitions.

If the current version needs to be kept, perhaps we can add an option that would allow the `outer` method to be called?

Open to ideas, or someone telling me why this is a horrible idea :smile:

**Comment by ef4** [comment]
I think you're right, it's just an oversight that I'm using `width` instead of `outerWidth` in these two transitions. We should switch.

**Comment by ef4** [comment]
Closed via 8622f078a9558bd08ed4786dc9051158f0738f23
