### ISSUE TITLE
liquid-outlet causes error in ember-inspector's views pane

### ISSUE THREAD

**Issue by knownasilya** [ef4/liquid-fire#210]
See [this](https://github.com/emberjs/ember-inspector/issues/260) issue over on the ember-inspector repo.

**Comment by ziggurat** [comment]
It also seems that using liquid-outlet breaks the tree view in ember inspector.

**Comment by James1x0** [comment]
Bump for my own aggravation with this issue.

**Comment by knownasilya** [comment]
@James1x0 what version of Ember and LF are you using? I no longer see the issue with the latest 0.21 I think.

**Comment by James1x0** [comment]
I'm pinging @ziggurat's issue specifically. Can you view components and nested routes under liquid-outlet, liquid-if, etc. in the view tree?

**Comment by ef4** [comment]
@James1x0 That was a bug in ember-inspector that is fixed in master: https://github.com/emberjs/ember-inspector/pull/428

**Comment by James1x0** [comment]
@ef4 I just reinstalled ember inspector and it fixed the issue. Guessing that it was bugged, as I had the latest version already.
