### ISSUE TITLE
liquid-spacer grows width by 2px with every grow or shrink

### ISSUE THREAD

**Issue by jasonporritt** [ef4/liquid-fire#211]
We noticed in our application that the width of a liquid-spacer was growing by 2 pixels each time we expanded or collapsed it. We also noticed that this same behavior manifests on the liquid-spacer example (see gif below).

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/338109/6732722/030d4a68-ce24-11e4-824e-7717d1f8b831.gif)

**Comment by abarax** [comment]
I can confirm this is also happening for my liquid spacer.

**Comment by abarax** [comment]
See pull request above for details on the issue and a failing test.  I have ways to fix the issue mentioned in the pull request but need someone who understands the wider ranging effects of the change.

**Comment by ef4** [comment]
I think I have a solution to this in #219. Please give it a whirl.

**Comment by abarax** [comment]
Yep, this will work.

**Comment by jasonporritt** [comment]
We're constrained to Ember 1.10 at the moment, but I applied that change to a fork of v0.17.1 and that does fix the growing behavior for us. Thanks!

**Comment by ef4** [comment]
Closed as of cd2a5fdc2b83b47f09d994f2f1d53832b6133b87
