### ISSUE TITLE
will-change CSS property

### ISSUE THREAD

**Issue by vectart** [ef4/liquid-fire#229]
> The will-change property allows you to inform the browser ahead of time of what kinds of changes you are likely to make to an element, so that it can set up the appropriate optimizations before they’re needed, therefore avoiding a non-trivial start-up cost which can have a negative effect on the responsiveness of a page. The elements can be changed and rendered faster, and the page will be able to update snappily, resulting in a smoother experience.
https://dev.opera.com/articles/css-will-change-property/

Since our application knows which CSS properties will be changes during transition, it's possible to set ```will-change``` property and let the browser to be prepared. I had already checked this wonderful feature on mobile website screen sliding and it's resulted in visible improvement. You can also try:
```css
.liquid-child {
  will-change: transform;
}
```

Should we implement that?

**Comment by ef4** [comment]
This is a good thing to do in apps, but it's not something we can easily bake into the library.

Not everybody is going to animate `transform`. There are lots of other possible animations that do other things instead. And `will-change` is not without cost & impact, so we don't want to mark every possible property as `will-change`.

This would be a good thing to write up in a list of performance tips.

**Comment by mirague** [comment]
@ef4 Is there any list of performance tips?
