### ISSUE TITLE
Cannot read property 'container' of undefined

### ISSUE THREAD

**Issue by eccegordo** [ef4/liquid-fire#232]
Using version 0.18.0 of liquid fire I am seeing an error 

```
Cannot read property 'container' of undefined
```

Could be something up with my app but error message seems to point to this line of code

https://github.com/ef4/liquid-fire/blob/v0.18.0/app/helpers/liquid-with.js#L7

```
    helperFunction: function liquidWithHelperFunc(params, hash, options, env) {
      var innerHash = {};
      var View = this.container.lookupFactory("view:liquid-with");
      var innerOptions = {
        hashTypes: {},
        morph: options.morph
      };

... snip ...
```

Interestingly the above seems to have been removed from master and liquidWithHelperFunc  is no longer in 

`liquid-fire/ember-internals`

Can some one explain what is happening here? Is there something I should look for in my code or just use master branch of liquid fire?

![liquid_with_error](https://cloud.githubusercontent.com/assets/497659/6974341/b81daf88-d946-11e4-8aa2-1089bbbfc928.png)

**Comment by ef4** [comment]
Please see #190 , this is the same issue.
