### ISSUE TITLE
liquid-with broken

### ISSUE THREAD

**Issue by dustinfarris** [ef4/liquid-fire#235]
This commit broke liquid-with for me:

https://github.com/ef4/liquid-fire/commit/628b2148738dc24002c01fdc728191a2931c8bf2

My usage is near verbatim from the docs, and as far as I can tell from the changelog there was no planned breaking change for the liquid-with helper.

**Comment by ef4** [comment]
Ugh, you're right. You must have a liquid outlet capturing the change.

We will need to revert this until we're ready to switch entirely to
liquid-outlet for model-to-model transitions.
