### ISSUE TITLE
Liquid Outlet inside Liquid If not working

### ISSUE THREAD

**Issue by sparkrevolutions** [ef4/liquid-fire#239]
I have a liquid outlet nested inside a liquid if (with an else clause):

```
{{#liquid-if login containerless=true class="inherit-height"}}
  {{liquid-outlet "login" class="inherit-height"}}
{{else}}
<div class="main">
  {{liquid-outlet class="auto-height content-view"}}
</div>
{{/liquid-if}}
```

Before upgrading to 0.19.2 (up from 0.14.0), this worked fine. Now I get the following error:

```
Uncaught TypeError: Cannot read property 'render' of undefined
```

My workaround at the moment, is to change both outlets and ifs to a regular ember equivalents - basically removing all traces of Liquid Fire from the project.

Ember: 1.11.0
Ember CLI: 0.2.2
Liquid Fire: 0.19.2

Any ideas?

**Comment by ef4** [comment]
Thanks. I was able to reproduce the problem. The issue is that a `{{liquid-outlet}}` that has no content will crash, but only when its parent outlet remains stable since the previous transition.

**Comment by sparkrevolutions** [comment]
Thank you. Amazing framework btw!

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
