### ISSUE TITLE
enableGrowth=false not working for {{liquid-outlet}}

### ISSUE THREAD

**Issue by bravo585** [ef4/liquid-fire#246]
enableGrowth=false doesn't seem to work. I have a {{liquid-outlet}} with widths and heights that change as the content changes. I want these width/height changes to happen immediately, not smoothly. Here's what I have:

{{liquid-outlet enableGrowth=false}}

**Comment by ef4** [comment]
Thanks for the bug report.

It looks like all the growth properties are not being passed through the underlying liquid-container, so `enbleGrowth`, `growDuration`, and `growEasing` are all being ignored.

**Comment by davewasmer** [comment]
As far as I can tell, it's impossible to speed up transitions faster than the default values thanks to this bug, which is what brought me here.

Looks like this is true for `liquid-if`, potentially others as well. @ef4 is this as simple as passing the values through in the template? I.e. adding `enableGrowth=enableGrowth growDuration=growDuration ...` on [this line](https://github.com/ef4/liquid-fire/blob/master/app/templates/components/liquid-if.hbs#L11)?

If so, happy to submit a PR with the changes.

**Comment by ef4** [comment]
Yes, I think that should fix it, go for it. The same probably applies to the other helper templates too.

**Comment by davewasmer** [comment]
PR created: #271

**Comment by ef4** [comment]
Closed via #271

**Comment by janwerkhoven** [comment]
Hi, so how does one fix this?

I have got `{{liquid-outlet "modal" growDuration=9000}}` in my application component, but the duration is ignored. I tried add `enableGrowth=enableGrowth growDuration=growDuration` to the containing component, but to no avail...

Any ideas?

**Comment by davewasmer** [comment]
@janwerkhoven I assume you mean `enableGrowth=false`, right?

**Comment by janwerkhoven** [comment]
So currently the `{{liquid-outlet "modal" growDuration=9000}}` is within the template of my component `{{hd-application enableGrowth=enableGrowth growDuration=growDuration}}`. Is it necessary to pass `enableGrowth` and `growDuration` into the component?

**Comment by ef4** [comment]
`growDuration` and `growPixelsPerSecond` work together to determine the behavior. See http://ember-animation.github.io/liquid-fire/#/helpers

If we only used duration, small changes look weird because they move so slowly. So `growPixelsPerSecond` sets a minimum speed for the movement.

**Comment by janwerkhoven** [comment]
Success!

```{{liquid-outlet "modal" growDuration=9000 growPixelsPerSecond=1}}```

Did the trick. Thanks guys :)

On a different not: Being able to animate the transition between 2 pages, between 2 virtual outlets is to me one of the best things that has happened to Ember. Keep it up! However, I must be honest, your documentation is quiet poor. I'm a front-end gun / designer at HotDoc. I wouldn't mind helping you guys out revamping and rewriting those stuffy documentations.

**Comment by ef4** [comment]
I am very happy to merge documentation PRs.

**Comment by janwerkhoven** [comment]
I'd be happy to help. Will let you know soon ;)
