### ISSUE TITLE
transition not applying

### ISSUE THREAD

**Issue by robpark** [ef4/liquid-fire#247]
This is very similar to #175 

I have a [simple new app](https://github.com/robpark/4animation) and I'm trying to apply animations, but I'm not seeing anything. Ideally, I was looking to get 'splash' route image to 'fly-to' the 'index' route image.

I assume I'm missing something very basic.

**Comment by ef4** [comment]
Thanks for putting together a demo to replicate your issues. I responded by doing a PR against your repo.

https://github.com/robpark/4animation/pull/1
