### ISSUE TITLE
Can't get initial load/start of liquid fire on Ember CLI project

### ISSUE THREAD

**Issue by amhasler** [ef4/liquid-fire#250]
I added liquid-fire to a very simple Ember-CLI project ( 0.2.3 ) by entering npm install --save-dev liquid-fire into the terminal. I added a transitions.js file: 

export default function(){  
  this.transition(
    this.fromRoute('index'),
    this.toRoute('works.work'),
    this.use('toUp'),
    this.reverse('toDown')
  );
}
Then replaced {{outlet}} with {{liquid-outlet}}. Now the views that formerly appeared in the {{outlet}} are not rendered. There were no errors to be found indicating that there was a problem.

As an experiment, I created a new transition so I could try out another liquid fire function, and added 

{{#liquid-width model as currentModel use="rotateBelow" class="demo-container"}}
  {{currentModel.id}}
  <button {{action "higher" currentModel}}>Go</button>
{{/liquid-with}}

to a template. It broke the page with the error "A helper named `liquid-width` could not be found"
This leads me to believe that liquid fire isn't being added to my project at all. None of the tutorials I read indicated an additional step, but am I missing an obvious step for adding this?

**Comment by ef4** [comment]
There is no `liquid-width`, it's `liquid-with`.

As for the content disappearing, take a look at the DOM and make sure your content isn't actually there but being rendered at zero size due to your CSS. liquid-outlet adds elements where outlet does not, so you may need to adjust your layout.

**Comment by amhasler** [comment]
I verified that I had in fact typed "liquid with" correctly in the code. I am still getting "Assertion Failed: A helper named `liquid-with` could not be found"

As for liquid-outlet, there are without a doubt no views being rendered when {{liquid-outlet}} is used.

Am I missing a step to get liquid fire to load in my project?

**Comment by ef4** [comment]
It's very weird that you aren't even able to load the library. What versions of ember and liquid-fire?

**Comment by amhasler** [comment]
It WAS weird. Several rounds of updates to ember, npm and the add-ons seems
to have fixed the problem. Can no longer replicated and seems to be working
okay now.

On Wed, Apr 15, 2015 at 1:01 AM, Edward Faulkner <notifications@github.com>
wrote:

> It's very weird that you aren't even able to load the library. What
> versions of ember and liquid-fire?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ef4/liquid-fire/issues/250#issuecomment-93189414>.
>



-- 
Adam Hasler
www.amhasler.com

**Comment by ef4** [comment]
Probably npm flakiness.
