### ISSUE TITLE
liquid-outlet not animating since update to 0.19.3

### ISSUE THREAD

**Issue by knownasilya** [ef4/liquid-fire#257]
Here is my outlet:

```hbs
{{liquid-outlet 'panel' class='panel-outlet' containerless=true}}
```
*Note: `containerless` isn't documented [here](http://ef4.github.io/liquid-fire/#/helpers) or [here](http://ef4.github.io/liquid-fire/#/helpers/liquid-outlet)* 

And my transitions:

```js
  // other transitions work.

  this.transition(
    this.hasClass('panel-outlet'),
    this.onInitialRender(), // was this.fromRoute(null)
    this.toRoute(function (name) {
      return name; // was this && this.length;
    }),
    this.use('toLeft')
  );

  this.transition(
    this.hasClass('panel-outlet'),
    this.toRoute(function (name) { // was this.toRoute(null)
      return !name;
    }),
    this.use('toRight')
  );
```

Debug:

```no-highlight
[liquid-fire rule 6] rejected because parentElementClass was ember-view application constraints.js:148
[liquid-fire rule 7] rejected because parentElementClass was ember-view application constraints.js:148
[liquid-fire rule 6] rejected because firstTime was no
```

**Comment by ef4** [comment]
`onInitialRender()` and `fromRoute(null)` do not mean the same thing.

`onInitialRender()` will limit your rule to only the first time the liquid-outlet renders. That is why the debug log says "rejected because firstTime was no". (I should probably change that messages so it says "because initialRender was no".) Whereas `fromRoute(null)` will limit your rule to when the outlet was empty before.

So I suspect something like this will do what you want:

```js
this.transition(
  this.hasClass('panel-outlet'),
  this.fromRoute(null),
  this.use('toLeft'),
  this.reverse('toRight')
);
```

**Comment by knownasilya** [comment]
@ef4 that makes sense. From the changelog/docs I was lead to believe that `onInitialRender()` replaced `fromRoute(null)`, guess not :smile: 

The example you provided doesn't work either. It was saying that newRoute was 'panels.layers', so I modified it and not it only says:

```no-highlight
[liquid-fire rule 6] rejected because parentElementClass was ember-view application
constraints.js:148 [liquid-fire rule 6 reverse] rejected because parentElementClass was ember-view application
```

Modified version:

```js
this.transition(
    this.hasClass('panel-outlet'),
    this.fromRoute(function (name) {
      return name && name.indexOf('panels.') === 0;
    }),
    this.use('toLeft'),
    this.reverse('toRight'),
    this.debug()
  );
```

**Comment by knownasilya** [comment]
@ef4 any idea what could be wrong? The app is located here: http://maldenma.mapgeo.alpha1.appgeo.com/

**Comment by knownasilya** [comment]
Ping?

**Comment by ef4** [comment]
I'm not able to isolate a repeatable bug here, please try to narrow down the problem. If you can start with an empty ember-cli app and demonstrate the broken behavior that would help me find it.

**Comment by knownasilya** [comment]
@ef4 should I be doing this with the latest glimmer based code?

**Comment by ef4** [comment]
If you're using the 0.19.x series on Ember 1.12 or earlier, that's fine too. I intent to support bugfixes on the `stable` branch for that.

**Comment by knownasilya** [comment]
@ef4 see https://github.com/knownasilya/lf-test

**Comment by knownasilya** [comment]
Just let me know if you need anything else.

**Comment by knownasilya** [comment]
@ef4 any ideas on what it might be?

**Comment by knownasilya** [comment]
@ef4 Still wondering if you had a chance to have a look? Thanks.

**Comment by Serabe** [comment]
@ef4 we are having the same issue. A few rare times it works, most of them, it does not. Furthermore, duration option is not being applied. We are looking into it.

**Comment by Serabe** [comment]
We downgraded to 0.19.2 and got it working. Then, upgraded to 0.19.4 again and it worked. Sorry I cannot give you more details on how to fix this.

**Comment by knownasilya** [comment]
Will give it a try.

**Comment by knownasilya** [comment]
Closing, since I'm pretty sure it was #340 that was the issue. Used `this.outletName('panel')` to solve the issue.
