### ISSUE TITLE
'superclass' of undefined

### ISSUE THREAD

**Issue by morgondag** [ef4/liquid-fire#261]
Upgrading to ``` 0.19.3 ``` from ```0.17.0 ```
I get the error 
```js
 Uncaught TypeError: Cannot read property 'superclass' of undefined
```

My main application.hbs look something like this

```hbs
        {{outlet "product"}}
        {{outlet "recipe"}}
        {{outlet "register"}}
        {{outlet "session"}}
        {{outlet "search"}}
        {{liquid-outlet}}
```

What am I missing?

**Comment by ef4** [comment]
The minimum Ember version supported by `0.19` is Ember 1.11. You should also be seeing a version warning in the console.

**Comment by hussfelt** [comment]
We're running Ember 1.10.0 it seems, but I cant be sure we did during this experimental update. Will get back to you!
