### ISSUE TITLE
Animation matches of elements during a modal transition are hidden

### ISSUE THREAD

**Issue by sglanzer** [ef4/liquid-fire#263]
I'm working with a few more complex than average modals.  In this case I want to instantly show the modal, but animate child elements.  However, while the overlay and container instantly appear, and the pick matches the new child element correctly, the child element disappears for the duration of the animation and re-appears completely unchanged.  I feel as though I'm missing something fundamental here:

```
this.transition(
        this.inHelper('liquid-modal'),
        this.toModal('application-search'),
        this.toValue(true),
        this.use('explode',
            {pickNew: '.lf-overlay', use: 'default'},
            {pickNew: '.lm-container', use: 'default'},
            {pickNew: '.application-search__cancel', use:
                function() {
                    var motion = {
                        translateX: 500,
                        translateY: 0,
                        outerWidth: this.newElement.outerWidth(),
                        outerHeight: this.newElement.outerHeight()
                    };

                    this.newElement.css({visibility: '', color: 'red'}); // Change the color before the animation
                    debugger; // Element is visible, but color change doesn't appear
                    return animate(this.newElement, motion, {duration: 5000}); // Disappears for the duration, no matter what properties are being animated
                }
            }
        )
    );
```

I'll keep digging through the code to see if I can find the root cause, but any direction would be appreciated.

**Comment by ef4** [comment]
I think your main problem is the z-index on the `.application-search__cancel` element. It's animating behind the modal overlay.

Also, your translateX will start it in its final position and animate it to the right 500px. If you want it to animate in instead, you can use velocity's forcefeeding by passing `translateX: [0, 500]`, meaning "go to zero, starting at 500".

Here's an example that I tested:

```js
  this.transition(
    this.inHelper('liquid-modal'),
    this.toValue(true),
    this.use('explode', {
      pickNew: '.application-search__cancel',
      use: function() {
        var motion = {
          translateX: [0, 500]
        };
        this.newElement.css({zIndex: 11});
        return animate(this.newElement, motion, {duration: 2000});
      }
    })
  );
```

**Comment by sglanzer** [comment]
@ef4 Thanks, I'll confirm this tomorrow in my environment and close as appropriate

**Comment by sglanzer** [comment]
Confirmed, this is working properly, thanks @ef4!
