### ISSUE TITLE
liquid-child adds inline style and breaks CSP rules

### ISSUE THREAD

**Issue by SlexAxton** [ef4/liquid-fire#264]
https://github.com/ef4/liquid-fire/blob/master/app/components/liquid-child.js#L4-L7 will cause this error:

![https://s3.amazonaws.com/f.cl.ly/items/1s3T0X2D3r2L032Z0u2Q/Screen%20Shot%202015-04-21%20at%203.48.12%20AM.png](https://s3.amazonaws.com/f.cl.ly/items/1s3T0X2D3r2L032Z0u2Q/Screen%20Shot%202015-04-21%20at%203.48.12%20AM.png)

I'd rather not turn on `unsafe-inline` - would it be possible to use a class here instead? Happy to PR if that's amenable.

/cc @michelle

**Comment by ef4** [comment]
There are a lot of places where we need inline styles. For example, when you use a transition like `toLeft` we set the transform property to potentially thousands of different values. As far as I know this needs to be inline. 

I would be happy to find a way to be compatible with stricter CSP, but I don't know if it's practical.

**Comment by SlexAxton** [comment]
Awesome. CSP without `unsafe-inline` would block setting the `style` attribute on an element, because that's a vector for security vulnerabilities, but it doesn't block the DOM APIs for manipulating individual style properties.

In other words, instead of setting the `style` attribute to `"left: 897px;"` we can do `domElement.style.left = "897px";` and that'd be alright. More importantly, we can just use `jQuery.fn.css`  (e.g. `this.$('.too').css('left', '897px');`).

So if it's cool, I'll PR a fix for this specific issue to see if it works for you guys (I'll cache the element that needs styling in `didInsertElement` and then just add an observer to the same property that's currently bound to `style` and update the cached element on changes)

If that works the way you guys want, I can try to identify some other/all places this occurs and help fix it.

Cool?

**Comment by ef4** [comment]
Sure, sounds good.
