### ISSUE TITLE
Deprecation warning for pickFiles and mergeTrees

### ISSUE THREAD

**Issue by jdhines** [ef4/liquid-fire#268]
After upgrading to ember-cli 0.2.3 and running `ember server` I get the following deprecation warnings due to what's in index.js:

````
[Deprecated] this.pickFiles is deprecated, please use broccoli-funnel directly instead  [addon: liquid-fire]
[Deprecated] this.mergeTrees is deprecated, please use broccoli-merge-trees directly instead  [addon: liquid-fire]
````
Fix appears to be outlined [here](http://www.ember-cli.com/#using-broccoli-funnel), using broccoli-funnel instead, but I'm not sure how to use that from within the already-installed liquid-fire module, as I haven't learned about addon development yet, or I'd do a pull request for this.

**Comment by jdhines** [comment]
Not sure whether this would be the fix or not, but wanted to try and see anyway:
https://github.com/jdhines/liquid-fire/commit/c033a036ea4ab3192f52fea6db7ff3310f5b63d6

**Comment by ef4** [comment]
Thanks, but this was already fixed [here](https://github.com/ef4/liquid-fire/pull/227).
