### ISSUE TITLE
using explode with DOM that's not quite ready

### ISSUE THREAD

**Issue by raycohen** [ef4/liquid-fire#285]
ember-list-view [schedules](https://github.com/emberjs/list-view/blob/f841d39d1141d66fd573bccf432837edd03c49e6/addon/list-item-view-mixin.js#L25) the application of the proper top and left values for its children.

In my application, I want to use an "explode" transition where a `pickNew` targets such a list view.  The problem that I run into is that the DOM is cloned just before it gets those positioning styles applied, and the list animates as an overlapping blob of items (all with top:0) rather than a list.

Is there some way for me to add a delay between when the DOM renders and when explode clones?

**Comment by ef4** [comment]
This is tricky. A delay is really not what you need, it would be hard to make that reliable. We would really need coordination between list-view and liquid-fire.

It may be possible to write a shim liquid-fire transition that finds the list view and waits for it to be ready before moving on to the rest of the animation.

**Comment by raycohen** [comment]
Yeah, the promise returned from a custom transition should give me a way to do this.
