### ISSUE TITLE
ember-cli@0.2.5 compatibility

### ISSUE THREAD

**Issue by buschtoens** [ef4/liquid-fire#287]
`liquid-fire` causes this error in the browser when using `ember-cli@0.2.5`:

```
Uncaught Error: Could not find module htmlbars-runtime
  internalRequire @ ember.debug.js:55
  requireModule @ ember.debug.js:39
  (anonymous function) @ ember-internals.js:14
  mod.state @ loader.js:141
  tryFinally @ loader.js:21
  requireModule @ loader.js:139
  requireFrom @ loader.js:112
  reify @ loader.js:97
  mod.state @ loader.js:140
  tryFinally @ loader.js:21
  requireModule @ loader.js:139
  (anonymous function) @ ember-load-initializers.js:23
  default @ ember-load-initializers.js:20
  (anonymous function) @ app.js:14
  mod.state @ loader.js:141
  tryFinally @ loader.js:21
  requireModule @ loader.js:139
  (anonymous function) @ app-boot.js:25
```

**Comment by buschtoens** [comment]
Not an error. Merely the wrong version.
`ember-cli@0.2.5` uses `ember@0.12.0`, which requires `liquid-fire@0.19.*`.

```
npm uninstall --save-dev liquid-fire
ember install liquid-fire@0.19.*
```

**Comment by elwayman02** [comment]
So how do you make it work with 0.20.0?

**Comment by buschtoens** [comment]
You'll need to upgrade Ember to 0.13.*.

**Comment by elwayman02** [comment]
Unfortunately, liquid-fire 0.20.0 throws compile errors with ember 1.13.x...I guess liquid-fire isn't quite ready for glimmer yet. :/

**Comment by ef4** [comment]
> Unfortunately, liquid-fire 0.20.0 throws compile errors with ember 1.13.x...I guess liquid-fire isn't quite ready for glimmer yet. :/

Liquid fire absolutely does work with Glimmer. [Here is our whole test suite](https://travis-ci.org/ef4/liquid-fire/builds/62600019) passing against canary. If you have a specific bug please report it.

**Comment by lessless** [comment]
jus got this with ember-cli 0.2.7 and "liquid-fire": "^0.20.2"

**Comment by raw1z** [comment]
Not working for me. I started a new projet with ember 1.13.0-beta.2, ember-cli 0.2.7 and liquid-fire 0.20.2.  I generated a new project with ember-cli and just replace {{outlet}} in app/template/appliction.hbs by {{liquid-outlet}}. I get the following error :

**Comment by ef4** [comment]
There are multiple different issues being confused in this thread.

@raw1z, your problem is being caused because liquid-fire already shipped an update to match a recent change on Ember canary, and the change on the Ember side has not yet shipped into a beta. I will talk to @rwjblue and figure out when it will ship so we can provide clear guidance on compatibility.

**Comment by ef4** [comment]
I confirmed that the Ember change will definitely ship in a 1.13 beta, and is already on the beta branch. So you can either run the Ember beta branch directly or wait for the next beta release to ship.

**Comment by raw1z** [comment]
ok thx
