### ISSUE TITLE
Is there an example for setting options for liquid-spacer?

### ISSUE THREAD

**Issue by jrjohnson** [ef4/liquid-fire#289]
http://ef4.github.io/liquid-fire/#/helpers/liquid-spacer indicates I can set growDuration, but I have no idea where that would be set.

**Comment by ef4** [comment]
```handlebars
{{#liquid-spacer growDuration=100}}
```

**Comment by jrjohnson** [comment]
Thanks, that actually is the first thing I tried, I think I was just animating the wrong block.  If it's something you want I can tweak the demo docs slightly to include this and do a PR.
