### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by e-karma** [ef4/liquid-fire#296]
Ember-CLI-0.2.6 + EmberJS 1.13.0-beta.2

liquid-measured.js:75 Uncaught TypeError: Cannot read property '0' of undefined

New Bug?   I'm fairly confident it's not my local setup..

**Comment by websymphony** [comment]
Try version 0.20.0 of liquid-fire which is compatible with glimmer engine update of ember.

```
ember install liquid-fire@0.20.0
```

**Comment by e-karma** [comment]
Worked great thanks!

**Comment by e-karma** [comment]
spoke too soon...  Getting very strange behavior in the addition/subtraction of dom inside the browser when using routes.. and the transitions aren't working.. 

at least 2 errors frequently are occuring and incorrect dom presentation 

Uncaught Error: Assertion Failed: Expected service:liquid-fire-transitions to resolve to an Ember.Service but instead it was (unknown mixin).

Another deprecation was something about mis-use of didInsertElement and performance
