### ISSUE TITLE
Uncaught Error: Assertion Failed: Expected service:liquid-fire-transitions to resolve to an Ember.Service but instead it was (unknown mixin).

### ISSUE THREAD

**Issue by e-karma** [ef4/liquid-fire#297]
Ember 1.13.0-beta.2
Ember-Data 1.17 & 1.18 beta (same error/result)
 
In addition to all these deprecations that are blocking the ember-inspector from working.  Am I missing a thread somewhere about how to work w/ glimmer-betas & canary?

**Comment by markr79** [comment]
+1

**Comment by e-karma** [comment]
anything?  If its going to be a couple weeks until its safe to use Liquid-fire and glimmer thats fine, it would just be good to know that so we can focus on other things.

**Comment by ef4** [comment]
This is fixed in the latest liquid-fire, and it was also made into a non-breaking warning in the latest Ember canary.

**Comment by ef4** [comment]
For reference: https://github.com/ef4/liquid-fire/pull/294
