### ISSUE TITLE
Ember 1.13.0-beta 2 does not work with latest LF@0.20.4

### ISSUE THREAD

**Issue by mattma** [ef4/liquid-fire#303]
I have a working application which is running on 

```bash
Library                    Version
Ember Inspector     1.8.1
Ember                     1.13.0-beta.2+fd51a87c
Ember Data             1.0.0-beta.18
jQuery                      1.11.3
Ember Simple Auth   0.8.0-beta.2
```
I did not have liquid fire installed in this app before. Without liquid fire, everything works out as expected. 

Then I tried out Liquid-fire, 'ember install liquid-fire', it installed the latest LF@0.20.4

```bash
// package.json
    "liquid-fire": "0.20.4",
```

I have tried with or without any constraint on transition map. It both run to the same issue. 

```bash
ember-internals.js:99 
Uncaught TypeError: Cannot read property 'childWithOutletState' of undefined
```

If I change the {{liquid-outlet}} to {{outlet}}, it works again. But with  {{liquid-outlet}}, it will run into the exception above.

**Comment by Eptis** [comment]
I also have this issue on ember 1.13.0-beta.1

**Comment by mattma** [comment]
@Eptis Thank you for verifying the problem. That is a good catch. @ef4 Any ETA on this?

**Comment by ef4** [comment]
You can either wait for Ember to release 1.13.0-beta.3, or switch directly to the beta channel with `bower install --save ember#beta`.

(It is somewhat confusing, but "latest Ember beta release" and "Ember beta channel" are not the same thing. There are often unreleased changes on the beta channel. We stay compatible with the beta channel. Usually the difference doesn't matter, but in this case Ember broke a key private API we use in the middle of the beta series.)

**Comment by Eptis** [comment]
Thanks for explaining! Will subscribe to the beta channel :)



—
Met vriendelijke groet / Kind regards,


Dennis Tel

**Comment by mattma** [comment]
It works out of box with Ember Beta 2.0.0. Thanks.
