### ISSUE TITLE
Actions not registered during animation/transition

### ISSUE THREAD

**Issue by kylesuss** [ef4/liquid-fire#306]
Hello! Great library, thanks for the hard work.

I am currently working on some modal animations using `liquid-modal`. Transition mapping is going well so far and I have some custom animations in place but I notice that some important actions (`outsideClick` and my own custom component actions) don't fire _during_ the time that Velocity is animating the element. I have to wait for the animation to complete in order to do anything inside the modal.

I understand that there are essentially duplicate copies of the transitioning elements in the DOM to create the effects, so does this mean that the issue I am facing is a limitation of the library? Is the only way to get around this to speed up the animations/transitions?

Btw, this is reproducible on the interactive documentation [here](http://ef4.github.io/liquid-fire/#/modals). Just click the black overlay before the modal finishes animating in and nothing happens, despite the appearance that the user is in fact clicking the overlay.

If you can think of a potential path to a solution, I'm happy to submit code. Just looking for a little guidance.

Cheers!

**Comment by ef4** [comment]
Apologies for the slow reply. I'm happy to leave this open until we have some better solution.
