### ISSUE TITLE
Liquid Fire injects code into the app namespace, which confuses code coverage

### ISSUE THREAD

**Issue by ForSpareParts** [ef4/liquid-fire#307]
Liquid Fire currently injects a number of modules into the app namespace: in particular, many in [app-name]/transitions/ and [app-name]/components. By default, when running code coverage with ember-cli-blanket, modules are filtered based on whether or not they're part of the app namespace. This means that a large number of special exclusion rules are required to distinguish Liquid Fire's code from the app's own.

I'm assuming that, at least for the components, the intent is to make these modules accessible to templates. Is there another way to accomplish that, or is it currently a limitation of Ember?

**Comment by ef4** [comment]
It is intentional that addons can add their code to the app namespace.

It sounds like ember-cli-blanket should be looking at an earlier point in the build pipeline so it can distinguish app-provided and addon-provided code.

**Comment by sglanzer** [comment]
@ForSpareParts We have an open issue on ember-cli-blanket to identify addon code and only cover application code.  Unfortunately nobody involved with the project has had time to work on this recently.  Either way, it's an ember-cli-blanket problem, not an issue with liquid-fire.
