### ISSUE TITLE
Check if app has liquid-fire installed

### ISSUE THREAD

**Issue by samselikoff** [ef4/liquid-fire#316]
I'm writing an addon and I'd like to be able to check from a component if the host app has liquid-fire installed. What would be the best way to do this?

**Comment by ef4** [comment]
You could check to see if the liquid-fire-provided component that you want is available in the container, in your own initializer or service:

    !!container.lookupFactory('component:liquid-if')

**Comment by samselikoff** [comment]
Trying an initializer:

```js
// addon/initializers/liquid-fire-detection.js
export function initialize( container ) {
  var lfDetection = container.lookup('service:liquid-fire-detection');
  lfDetection.set('hasLiquidIf', !!container.lookupFactory('component:liquid-if'));
}

export default {
  name: 'liquid-fire-detection',
  initialize: initialize
};
```

Bizarrely, the `!!container.lookupFactory('component:liquid-if')` call causes all liquid-ifs in my app to not work - they always render their contents, and don't respond to data updates. I don't see any errors or other messages in the console, just a deprecation warning about `lookupFactory`.

Any ideas? Thanks!

**Comment by bcardarella** [comment]
@samselikoff you likely want to use an instance initializer, not an initializer

**Comment by samselikoff** [comment]
ok, I moved the code to an instance initializer, used `instance.container.lookup('component:liquid-if')` and I'm getting the same behavior - `{{#liquid-if}}` stops functioning. I'll keep digging.

**Comment by samselikoff** [comment]
Ok I confirm behavior exists in a brand new app, in both an initializer and an instance initializer.

Steps to reproduce:

1. `ember new liquid-fire-test`
2. `npm install --save-dev ef4/liquid-fire#stable`
3. In `application.hbs` add

    ```hbs
    {{input type='checkbox' checked=isShowing}}

    {{#liquid-if isShowing}}
      <p>Foo</p>
    {{/liquid-if}}
    ```

    and verify the checkbox toggles the liquid-if.

4. `ember g initializer liquid-fire-checker`
4. In the `initialize` function, add

    ```js
    export function initialize(container) {
      console.log(!!container.lookupFactory('component:liquid-if'));
    }
    ```

    This could also be `container.lookup`, or you could also use an instance-initializer.
5. Run the app again, and you'll see the `{{#liquid-if}}` block is no longer functioning. The panel is open and doesn't respond to the checkbox.

**Comment by rwjblue** [comment]
I think it would be easier to detect and add a boolean flag to your addons config.  You can use [ember-cli-version-checker](https://github.com/rwjblue/ember-cli-version-checker) to detect if `liquid-fire` is present (and check its version if you care) in the host app, then set a config value in your addon's `config` hook (or `config/environment.js`).

See a super long winded explanation of tailoring an addon's output tree based on available packages: https://github.com/ember-cli/ember-cli/issues/4339#issuecomment-115384427

**Comment by samselikoff** [comment]
@rwjblue ok, this is actually for an addon. I'm not sure if it's possible for my addon to rely on another addon yet?

**Comment by rwjblue** [comment]
@samselikoff - Yes, many cases of nested addons work today (but some do not).  The technique that I was suggesting was unrelated to nested addons though, ember-cli-version-checker is not an addon (it is a utility function/library).

**Comment by samselikoff** [comment]
Got it - works great. thanks!
