### ISSUE TITLE
Issues with ember-cli 0.2.7

### ISSUE THREAD

**Issue by scolyer** [ef4/liquid-fire#325]
Hello,
I just tried to ember install liquid-fire and my app won’t load, citing this error message: "Uncaught Error: Could not find module htmlbars-runtime".

**Comment by scolyer** [comment]
I've fixed it - ember-cli installs 0.20 by default.

**Comment by Dragsbaek** [comment]
how did you fix it? I get the same error

**Comment by scolyer** [comment]
@Dragsbaek I did a few things, and what you should do depends on how you want your ember-cli environment set up.

**Option 1**
 Install the correct version of liquid-fire for ember 1.12 (which ships with ember-cli 0.2.7):
1) Uninstall liquid-fire
```bash
npm uninstall liquid-fire --save-dev
```
2) Re-install liquid-fire v 0.19 (ember 1.12 compatible)
```bash
ember install liquid-fire@^0.19.0
```

**Option 2**
Upgrade ember to 1.13 beta
1) Uninstall liquid-fire (just in case)
```bash
npm uninstall liquid-fire --save-dev
```
2) Update your bower.json file to use ember 1.13
```json
{
  "name": "yourapp",
  "dependencies": {
    "ember": "1.13.0",
   ...
}
```
3) tell bower to upgrade ember
```bash
bower install
```
4) Re-install liquid-fire
```bash
ember install liquid-fire
```

Hope that helps!
