### ISSUE TITLE
withinRoute() doesn't animate in liquid-fire 0.20.4 

### ISSUE THREAD

**Issue by dmoreno** [ef4/liquid-fire#332]
In a fresh new project with ember-cli 0.2.7, ember 1.13.3, and liquid-fire 0.20.4, I see transition made with withinRoute doesn't animate.

Here is a gist with the code:

https://gist.github.com/dmoreno/f398853ae750c882bb9a

when we go from admin route to content route, transition effect is ok. But when we go from content to content (inside liquid-with block), there is no transition effect. Same behaviour with:

```javascript
this.fromRoute('content'),
this.toRoute('content'),
```

I noticed this behaviour migrating from liquid-fire 0.17 and ember-1.10. Same code was working fine until migration.

**Comment by dmoreno** [comment]
I have updated issue description with a working example code using liquid-bind and withinRoute.

**Comment by ef4** [comment]
You're hitting one of the breaking changes in 0.19.0. From CHANGELOG:

> BREAKING: route constraints only apply to liquid-outlets. Other helpers like liquid-if used to try to figure out what route they were in so they could respect withinRoute constraints, but this is both complicated and not a good idea. Only outlets are supposed to know about routes -- each helper should only animate based on its own well-encapsulated state.

**Comment by ef4** [comment]
I suggest using a constraint like hasClass or matchSelector instead to control your liquid-with.

**Comment by dmoreno** [comment]
Thanks @ef4! You're right.

I fix it migrating liquid-with to liquid-bind and matching by value. It works like a charm!
