### ISSUE TITLE
real_outlet has been removed in Canary

### ISSUE THREAD

**Issue by rlivsey** [ef4/liquid-fire#336]
liquid-fire currently breaks against Canary because real_outlet (as [used here](https://github.com/ef4/liquid-fire/blob/2a399aa4f930353af3bfef158a23bb3279009705/addon/ember-internals.js#L12)) has [been removed](https://github.com/emberjs/ember.js/commit/9110babda1137d878b7fd8f758791dbaf684aa34)

From what I can see, `isStable` is now on 'outlet' vs 'real_outlet' so we should be able to replace:

```javascript
var isStable = require('ember-htmlbars/keywords/real_outlet').default.isStable;
```

with:

```javascript
var isStable = require('ember-htmlbars/keywords/outlet').default.isStable;
```

Also we'd need to detect which to require, is there a way to check before calling `require`?

**Comment by ef4** [comment]
Fixed in aee5ca3865cd95adaa34965addb0eec8f38da61b

**Comment by ef4** [comment]
> Also we'd need to detect which to require, is there a way to check before calling require?

Maybe, but that whole use of require is private API, so all we're trying to do is keep up until we can codify a public API in Ember that accomplishes the same thing.

**Comment by rlivsey** [comment]
ah yes, `try…catch`, not sure why I didn't think of that first!

Cheers
