### ISSUE TITLE
showing different modals for the same query key but different value

### ISSUE THREAD

**Issue by berdof** [ef4/liquid-fire#339]
I want that query `?modal=photo` would open `photoModal` and `?modal=video` would open `videoModal` . To do this I added this code to my router.js :

 ` this.modal('photoModal', {
    withParams: [{modal:'photo'}],
    dialogClass:'modal-photo'
  });`

  `this.modal('videoModal', {
    withParams: [{modal:'video'}],
    dialogClass:'modal-photo'
  });`

But it didn't work as it was expected and no meter what value I pass for `modal` query it always shows me `videoModal` . 
I think it would be great to show different modals for one query key but it's different values. Otherwise it doesn't matter what value do we pass for query key.

**Comment by ef4** [comment]
This:

```js
this.modal('photoModal', { withParams: [{modal:'photo'}], dialogClass:'modal-photo' });
```

Means "show the `photoModal` whenever the `modal` property on my controller has a non-default value. Set that value as the `photo` property on my `photoModal` component.

To get the behavior you want, just make computed properties on your controller:

```js
  showPhoto: Ember.computed.equal('modal', 'photo'),
  showVideo: Ember.computed.equal('modal', 'video')
```

```js
this.modal('photoModal', { withParams: 'showPhoto', dialogClass:'modal-photo' });
this.modal('videoModal', { withParams: 'showVideo', dialogClass:'modal-video' });
```

**Comment by phcoliveira** [comment]
I am trying your suggestion: having a computed property on the controller to determine if the modal should be opened, but, even when it evaluates to false in the first run, the application bootstraps itself with such modal opened.

In order to get it done, I am using:
```
showUserModal: Ember.computed('modal', function() {
    return this.get('modal') === 'user' ? true : undefined;
})
```
