### ISSUE TITLE
Liquid Outlet and Scroll Distance

### ISSUE THREAD

**Issue by hhff** [ef4/liquid-fire#349]
Hi @ef4 !

Trying out Liquid Fire again.  I've got a problem I can't quite figure out - it seems like a fairly common stumbling block, but I can't find any documentation on it.

I'm defining a transition between two top level routes (`home` -> `posts`)

`home` is a page that is taller than the viewport.

When the user scrolls down on the `home` template, and then initiates the transition to `posts`, the `home` template jumps back to the top of the page due to the absolute positioning.

I would like for the `home` template to keep its scroll offset during the transition.  Is this possible?

**Comment by hhff** [comment]
Just wanted to bump this - need to make a decision on liquid fire before wednesday, and this is make or break.

**Comment by ef4** [comment]
Yes, it's possible. It sounds like you're doing full-viewport animation, so I would suggest making your topmost liquid-outlet fixed at 100% of the viewport size, and allow your content to scroll inside that. Then you have full control over how it animates and scrolls.

**Comment by ef4** [comment]
Also see my memory-scroll repo for an add-on that helps with the opposite case -- returning to the same scroll position that you left.

**Comment by hhff** [comment]
Thanks @ef4 - I was about to implement the viewport size technique, but I realized that would mean those views on iOS would have no scroll inertia, right?

**Comment by rlivsey** [comment]
@hhff you can add inertial scrolling back in by setting `-webkit-overflow-scrolling: touch;`

https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

**Comment by hhff** [comment]
@rlivsey that's a game changer.  case closed !!
