### ISSUE TITLE
custom template resolver

### ISSUE THREAD

**Issue by khemer** [ef4/liquid-fire#356]
Hello,

the plugin is not working when we customize the template resolver:

<code>
app.js
Resolver.reopen({
	resolveTemplate: function(parsedName) { .... }
});
</code>

any idea how to resolve it?

Thanks

liquid-fire: 0.21.2
ember-cli: 1.13.1
npm: 2.10.1

**Comment by khemer** [comment]
Hello,

I found the problem.
We customize the resolver template path to <code>template/new_folder/*.hbs</code> thus the problem occur.

We solved it, by tweaking the liquid-fire path <code>/node_modules/liquid-fire/app/templates/*.hbs</code> to <code>/node_modules/liquid-fire/app/templates/new_folder/*.hbs</code>

Sorry for the inconvenience

**Comment by ef4** [comment]
Ok, sounds good.

You may want to figure out how to make your custom resolver also work with the standard paths, because this is the standard way for addons to inject templates into the application.
