### ISSUE TITLE
Ember 2.0 Compatibility?

### ISSUE THREAD

**Issue by coladarci** [ef4/liquid-fire#360]
There was a lot of talk in this post http://emberjs.com/blog/2015/06/16/ember-project-at-2-0.html about `Liquid Fire 2.0 beta` coming out in June and I'm interested to know what the status is? I see no branch, commits or conversation about it so I'm starting to wonder if I'm looking in the wrong place!

**Comment by ef4** [comment]
Everything in liquid-fire 0.21 is compatible with Ember 2.0.

I do still intend to ship a version bump just to communicate more clearly, but no API is going to change in that release.
