### ISSUE TITLE
Why transition not work?

### ISSUE THREAD

**Issue by marucjmar18** [ef4/liquid-fire#361]
Hey,

Application schema:

application.hbs
```javascript
{{liquid-oulet}}
```

index.hbs
```javascript
{{liquid-oulet}}
```
in index/pictures.hbs
```javascript
{{#link-to 'picture.show' picture}}
      Go
{{/link-to}}
```

link from route: index.pictures to route: pictures.show

It working transition.js:
```javascript
  this.transition(
    this.toRoute('picture'),
    this.use('toLeft', {duration:500}),
    this.reverse('toRight', {duration:500})
  );
```

It doesn't work why? transition.js:
```javascript
  this.transition(
    this.toRoute('picture.show'),
    this.use('toLeft', {duration:500}),
    this.reverse('toRight', {duration:500})
  );
```
ember-cli@1.13.8
liquid-fire: 0.21.2

**Comment by ef4** [comment]
Each outlet only handles one level of the route hierarchy. This is not liquid-fire specific, it is how all Ember apps work.

An outlet (or liquid-outlet) in application.hbs will only ever see transitions into `picture`, never `picture.show`. `picture.show` is instead handled by an outlet (or liquid-outlet) inside picture.hbs.
