### ISSUE TITLE
Position: fixed not working in liquid-container

### ISSUE THREAD

**Issue by IgorKvasn** [ef4/liquid-fire#368]
Hi,
I wanted to create a DIV inside a *liquid-container* with the following class:
```
.my-div{
position:fixed; 
bottom:0; 
}
```

However the DIV wasn't behaving as expected - instead of being sticked at the bottom of the window (so that when you scroll on the page, it will be always at the bottom of the current viewport), it was placed at the very bottom of the liquid-container (just like with *position:absolute*).

As it turned out, the liquid-container has *transform: translateY(0);* that is messing with DIV's position. So I made this workaround:

```
.liquid-container {
  -webkit-transform: none;
  -moz-transform: none;
  transform: none;
}

.liquid-animating .liquid-container {
    -webkit-transform: translateY(0);
    -moz-transform: translateY(0);
    transform: translateY(0);
}
```
I am really not sure if this is a correct way to fix this issue, though...

btw. wouldn't it be better to apply all the styles specific liquid-fire with liquid-animating class? So that issues like this one or #208 wouldn't happen?

**Comment by runspired** [comment]
@IgorKvasn the translateY is there to force GPU acceleration where possible.  Unfortunately, GPU acceleration does currently break fixed positioning.

I'm not sure, but at least on Chrome it *may* behave differently if you use [will-change](http://caniuse.com/#feat=will-change)

**Comment by ef4** [comment]
`will-change` is a superior replacement for `translateY(0)` on browsers that support it.

Adding `translateY` only at the start of animation defeats the point of having it there -- it exists to force consistency between how the layer will look both before and during animation. Without it there are cases where your apparent colors and text positions can jump, due to different subpixel rendering implementations.

**Comment by IgorKvasn** [comment]
so if I understand it correctly - there is no way to fix this, since `will-change` works only on couple of browsers and I cannot remove `translateY(0)`, right?

**Comment by runspired** [comment]
@IgorKvasn yes, basically.  Here's an article on it: http://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/

**Comment by IgorKvasn** [comment]
this is just sad :(
thanks guys

**Comment by ef4** [comment]
To be clear: if your app looks fine in the browsers you care about without `translateY`, it's totally fine to use your CSS to strip it out, as you showed above. It's there in the library to protect people from the cases that don't look good.

**Comment by dustinfarris** [comment]
I don't fully understand how to leverage `will-change` here.
