### ISSUE TITLE
app.scss merge error

### ISSUE THREAD

**Issue by funtusov** [ef4/liquid-fire#389]
On ember-cli 1.13.12, ember-cli-sass 5.1.0 and ember-component-css 0.1.6 the app build fails with:

```Merge error: file app/styles/app.scss exists in [..]/tmp/broccoli_merge_trees-input_base_path-nOkLWQOU.tmp/25```

Deleting the styles.scss within node_modules/liquid-fire/app/styles/ fixes the error. Probably similar to https://github.com/tim-evans/ember-page-title/issues/21

**Comment by anil28** [comment]
There was no styles.scss. But deleting  **app.scss** within node_modules/liquid-fire/app/styles/ fixed the error

**Comment by funtusov** [comment]
of course, ``app.scss``, sorry :)

**Comment by ancashoria** [comment]
We have the same problem. Anyone got a permanent fix ?

**Comment by samselikoff** [comment]
Ran into the same problem, deleting `node_modules/liquid-fire-app/styles/app.scss` fixed the problem. But need a permanent fix.

**Comment by ankushdharkar** [comment]
I also ran into the same problem with ` ember-cli 1.13.13`, `ember-cli-sass 5.2.0` and `ember-component-css 0.1.6`. Fixed it by doing what others here did : Deleted `node_modules/liquid-fire/app/styles/app.scss`.
