### ISSUE TITLE
Transitions are not working

### ISSUE THREAD

**Issue by Jordan4jc** [ef4/liquid-fire#391]
I just installed the addon in ember-cli, I'm using `1.13.7` and I created my `transitions.js` copying from the demo app like so

    import Ember from "ember";

    export default function(){
      if (Ember.testing) {
        this.setDefault({duration: 10 });
      }
      this.transition(
  	    this.fromRoute('items'),
  	    this.toRoute('item'),
  	    this.use('toLeft'),
  	    this.reverse('toRight')
      );
    }

But when I go to link from an item in `items` to link-to the `item` route no transition happens either way.

I also tried specifying the index route like `items.index` and `item.index` but still no dice, I've used this addon before but I just installed and ran with it and it worked fine.

**Comment by ef4** [comment]
Did you put a liquid-outlet somewhere?

**Comment by Jordan4jc** [comment]
I did just now, however it still doesn't show the animations. But the `item` route is also not a nested route, it's separate from `items` so that's why I wasn't using an outlet in the first place.

**Comment by ef4** [comment]
Add `this.debug()` inside your transition rule. It will tell you the names
of the routes that the outlet is actually seeing.

**Comment by Jordan4jc** [comment]
I'm seeing blanks

[liquid-fire] Checking transition rules for `<div id=​"ember772" class=​"ember-view liquid-container">​…​</div>​`
constraints.js:150 [liquid-fire rule 1] rejected because oldRoute was
constraints.js:150 [liquid-fire rule 1 reverse] rejected because oldRoute was
constraints.js:150 [liquid-fire rule 1] rejected because newRoute was
constraints.js:150 [liquid-fire rule 1 reverse] rejected because newRoute was
constraints.js:150 [liquid-fire rule 1] rejected because firstTime was yes
constraints.js:150 [liquid-fire rule 1 reverse] rejected because firstTime was yes

**Comment by ef4** [comment]
So your liquid-outlet is rendering with nothing in it. That would be the
case if it's in the wrong place, like if it's inside a template that
doesn't actually have any active nested child routes below it.

**Comment by Jordan4jc** [comment]
Ah so I need to put it in the application template. Okay that's working now, but the animation looks quite strange, I'll make another issue to explain if I don't figure out what's happening, thanks.
