### ISSUE TITLE
Update documentation: add a quick start

### ISSUE THREAD

**Issue by frederikbosch** [ef4/liquid-fire#400]
Some people seem to have a problem with getting Liquid Fire to work because they do not include `{{liquid-outlet}}`. The problem is two fold: they do not include the outlet at all, or they forget, like me, to include multiple outlets. My suggestion would be to overcome this situation with a **quick start** in the documentation.

This quick start has to demonstrate how to embed Liquid Fire into your Ember application. My suggestion would be to include the following, all with code example of course.

- [x] add transition to transitions.js
- [x] add liquid-outlet to application.hbs
- [x] add transition for child route to transitions.js
- [x] add liquid-outlet for child route

If you feel this is a bad idea, close this issue. Otherwise, I might help on the PR.

**Comment by ef4** [comment]
This sounds good. It could also be a "Cookbook" section instead of quick start, then we can keep adding scenarios that trip people up.

**Comment by frederikbosch** [comment]
Wonderful. Will see if I can come up with a PR soon.

**Comment by frederikbosch** [comment]
@ef4 Why not merge #403? Maybe you comment what you expect to be changed?
