### ISSUE TITLE
Numerous of people seem unable to get their first transition going in Ember CLI

### ISSUE THREAD

**Issue by janwerkhoven** [ef4/liquid-fire#406]
Hi,

According this [question](http://stackoverflow.com/questions/29550501/added-liquid-fire-to-ember-cli-project-liquid-outlet-does-nothing) there are numerous of people that unable to get their first transition to work, including me. Would it not be useful to add a "Get Started" section to your website with numbered steps that guarantee a first transition within an Ember CLI app? I'm sure this will help many people!

What I tried is:

*In Ember CLI 1.13.13*

1. Ran `ember install liquid-fire`
2. Install successful, NPM says "Installed addon package."
3. Replaced the only `{{outlet}}` with `{{liquid-outlet}}`
4. Added `app/transitions.js` and entered this transition:
    ```javascript
    export default function() {  
      this.transition(  
        this.use('toLeft')  
      );  
    }  
    ```
   Assuming that defining no routes applies to all...

5. The ran `ember server`
6. All the content inside the `{{liquid-outlet}}` is shown correctly
7. The `{{liquid-outlet}}` content is correctly wrapped in `<div class="liquid-container">` and `<div class="liquid-child>"`
6. Clicked through my routes
7. Content shows correctly but **no animations**!
8. For a split second, I do see class `liquid-animation` being added

How can I solve this?

Is this a bug?

Should we make a step by step guide to help people onboard Liquid Fire?

PS: Love your work, this package has so much potential!

**Comment by janwerkhoven** [comment]
On this [branch](https://github.com/janwerkhoven/brenndel.com/tree/feature/ember) you can find my Ember app under construction. Please advise.

Could it be a faulty animation?
Could it be because views are being deprecated in Ember?
Use legacy view package?

**Comment by janwerkhoven** [comment]
**Update:**
Using an explicit transition does seem to work!
`{{liquid-outlet use="toLeft"}}`

So the issue lies with the transition map?

**Comment by janwerkhoven** [comment]
Apologies, I found what caused it. I place the `transitions.js` outside the `app/` folder. All works fine now. Sorry for the bother :)

**Comment by frederikbosch** [comment]
Another reason to merge #400.

**Comment by frederikbosch** [comment]
Please see the [cookbook in the documentation](http://ef4.github.io/liquid-fire/#/cookbook).
