### ISSUE TITLE
is it possible to define a wildcard on the from/to routes?

### ISSUE THREAD

**Issue by cimtico** [ef4/liquid-fire#413]
I'd like to have a default fade transition on all routes in the app, however defining all permutations of transitions just isn't feasible.

Is it possible to use wildcards on transition definitions?

**Comment by runspired** [comment]
@cimtico yes, just leave both `fromRoute` and `toRoute` off.

This one matches all transitions, including the very first one.
```
  this.transition(
    this.onInitialRender(),
    this.use('fade', { duration: 200 })
  );
```

Please post future `support` questions to the [#liquid-fire](embercommunity.slack.com/messages/liquid-fire) channel in the ember-community slack.

**Comment by ef4** [comment]
Yes, the above is correct. Also, for trickier situations you can also pass regular expressions to fromRoute and toRoute.
