### ISSUE TITLE
Incompatible with non-handlebars template preprocessors

### ISSUE THREAD

**Issue by drewcovi** [ef4/liquid-fire#93]
With the latest ember, the approach outlined in #55 no longer works, and clashes with existing templates.

`EEXIST, file already exists '/.../tmp/template_compiler-tmp_dest_dir-ozshUjvN.tmp/lyric/templates/liquid-with-self.js'
Error: EEXIST, file already exists '/.../tmp/template_compiler-tmp_dest_dir-ozshUjvN.tmp/lyric/templates/liquid-with-self.js'`

**Comment by ef4** [comment]
I think this was fixed when ember-cli switch to per-addon preprocessor registration.

**Comment by drewcovi** [comment]
excellent!
